export const store = {
    buttons: [
        { val: "C" },
        { val: "7" },
        { val: "8" },
        { val: "9" },
        { val: "*" },
        { val: "-" },
        { val: "4" },
        { val: "5" },
        { val: "6" },
        { val: "/" },
        { val: "+" },
        { val: "1" },
        { val: "2" },
        { val: "3" },
        { val: "=" },
        { val: "." },
        { val: "(" },
        { val: "0" },
        { val: ")" },
        { val: "CE" },
    ],
};
